# Generated by Django 6.0.1 on 2026-02-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('parent_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('family_id', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('medical_condition', models.CharField(default='No', max_length=10)),
                ('medical_details', models.CharField(blank=True, max_length=200)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_mobile', models.CharField(max_length=15)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('student_aadhaar', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('parent_aadhaar', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('student_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('parent_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
